### ISSUE TITLE
License validation

### ISSUE THREAD

**Issue by inxomnyaa** [MiniGameAPI-PM/MiniGameAPI#4]
Hello. I am here to friendly remind you, that due to the license of https://github.com/thebigsmileXD/gameapi, you are nit allowed to copy the repository and change the license/owner specific content without permission by the owner.

You can definitely see, that the code was copied from my repository whilest comparing these files:

https://github.com/JustD01t/MiniGameAPI/blob/master/src/minigameapi/Team.php
And
https://github.com/thebigsmileXD/gameapi/blob/master/src/xenialdan/gameapi/Team.php

I'd respect it, if you'd instead better fork and upgrade gameapi instead of stealing it.

Otherwise i'd have to create a DMCA request.

Thanks kindly, XenialDan.

**Comment by djdisodo** [comment]
I tried to compare it
https://github.com/djdisodo/gameapi/commit/bdbd953946bd711d1409e29d916b029a37f290c5

There are several similar functions and variables.
However, this is a simple function that is commonly used.
If I were willing to copy the code, I would have copied the text.
Why would I have to remove the typehint even if I deleted things I did not need?

I do not speak English well.
Please tell me if you do not understand.

**Comment by ghost** [comment]
I know that if you used GPL licensed code, then you need to change license to GPL or AGPL(or which is compatible with GPL 3.0v License) whether you removed or not. I know that if you don't want to change license to GPL 3.0v, then you need to revert the commit that you copied the GPL licensed code. Sorry for my bad English skill.  And I am sorry about the license problem @thebigsmileXD . I will talk to him as Korean(@djdisodo 's native language) to make him understood. Thank you.

ps. If I was wrong about the license, then tell me. Thank You.

**Comment by ghost** [comment]
I will leave it to your choice @djdisodo . You need to use GPL 3.0v license or revert the commit.

**Comment by inxomnyaa** [comment]
This is really kind of you guys <3 most developers i know are not so accommodating

**Comment by ghost** [comment]
Thanks for your kindness and I will close this because I think @djdisodo choose to revert the commit.


Ps. I like your plugins. :)
